@BallotCast_HostAddress = http://localhost:5109

### Get all referendums with eager loading
GET {{BallotCast_HostAddress}}/referendum/eager
Accept: application/json

###

### Get all referendums with lazy loading
GET {{BallotCast_HostAddress}}/referendum/lazy
Accept: application/json

###

### Get all referendums with explicit loading
GET {{BallotCast_HostAddress}}/referendum/explicit
Accept: application/json

###

### Create a new referendum
POST {{BallotCast_HostAddress}}/referendum
Content-Type: application/json

{
  "title": "New Policy",
  "question": "Do you support the new policy?",
  "paragraphs": [
    {
      "content": "This policy aims to improve environmental standards."
    },
    {
      "content": "It includes measures to reduce carbon emissions."
    }
  ],
  "options": [
    {
      "optionText": "Yes"
    },
    {
      "optionText": "No"
    }
  ],
  "status": "Pending"
}
Accept: application/json