@BallotCast_HostAddress = http://localhost:5109

### Get all referendums
GET {{BallotCast_HostAddress}}/referendum
Accept: application/json

###

### Create a new referendum
POST {{BallotCast_HostAddress}}/referendum
Content-Type: application/json

{
  "question": "Do you support the new policy?",
  "vote": true
}
Accept: application/json