// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BallotCast.Migrations
{
    [DbContext(typeof(ReferendumContext))]
    [Migration("20240718030300_UpdateReferendumModel")]
    partial class UpdateReferendumModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("OptionResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("OptionText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReferendumResultId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VoteCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ReferendumResultId");

                    b.ToTable("OptionResult");
                });

            modelBuilder.Entity("Paragraph", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReferendumId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ReferendumId");

                    b.ToTable("Paragraph");
                });

            modelBuilder.Entity("Referendum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("ResultId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ResultId");

                    b.ToTable("Referendums");
                });

            modelBuilder.Entity("ReferendumOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("OptionText")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReferendumId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VoteCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ReferendumId");

                    b.ToTable("ReferendumOption");
                });

            modelBuilder.Entity("ReferendumResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ResultDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ReferendumResult");
                });

            modelBuilder.Entity("OptionResult", b =>
                {
                    b.HasOne("ReferendumResult", null)
                        .WithMany("OptionResults")
                        .HasForeignKey("ReferendumResultId");
                });

            modelBuilder.Entity("Paragraph", b =>
                {
                    b.HasOne("Referendum", null)
                        .WithMany("Paragraphs")
                        .HasForeignKey("ReferendumId");
                });

            modelBuilder.Entity("Referendum", b =>
                {
                    b.HasOne("ReferendumResult", "Result")
                        .WithMany()
                        .HasForeignKey("ResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Result");
                });

            modelBuilder.Entity("ReferendumOption", b =>
                {
                    b.HasOne("Referendum", null)
                        .WithMany("Options")
                        .HasForeignKey("ReferendumId");
                });

            modelBuilder.Entity("Referendum", b =>
                {
                    b.Navigation("Options");

                    b.Navigation("Paragraphs");
                });

            modelBuilder.Entity("ReferendumResult", b =>
                {
                    b.Navigation("OptionResults");
                });
#pragma warning restore 612, 618
        }
    }
}
